spaces_wiki/urls.py
from django.conf.urls import url
from django.urls import include, path, re_path
from django.utils.module_loading import import_string

from wiki.urls import WikiURLPatterns, get_pattern as get_wiki_pattern
from wiki.views import article
from spaces.urls import space_patterns



from . import views

class SpaceWikiURLPatterns(WikiURLPatterns):
    """
        for subclassing and extending the views of django-wiki
    """
    article_view_class = views.SpaceArticleView
    article_create_view_class = views.SpaceCreate
    article_delete_view_class = views.SpaceDelete
    article_deleted_view_class = views.SpaceDeleted
    article_diff_view = views.SpaceDiffView
    article_dir_view_class = views.SpaceDir
    article_edit_view_class = views.SpaceEdit
    article_preview_view_class = views.SpacePreview
    article_history_view_class = views.SpaceHistory
    article_settings_view_class = views.SpaceSettings
    article_source_view_class = views.SpaceSource
    article_plugin_view_class = views.SpacePlugin
    revision_change_view_class = views.SpaceChangeRevisionView
    root_view_class = views.SpaceIndex

    def get_root_urls(self):
        urlpatterns = [
            re_path('^$',
#                self.article_dir_view_class.as_view(),
                self.root_view_class.as_view(),
                name='root',
                kwargs={'path': ''}),
# Disabled for now
#            url('^_search/$',
#                import_class(self.search_view_class).as_view(),
#                name='search'),
            re_path('^_revision/diff/(?P<revision_id>[0-9]+)/$',
                self.article_diff_view,
                name='diff'),
        ]
        return urlpatterns


spaces_wiki_url_patterns = [
        re_path(r'^notes/', get_wiki_pattern(
        namespace=None,
        url_config_class=SpaceWikiURLPatterns
        )
    ),
]

# dirty hack to prevent code duplication:
# django-wiki's decorator get_article() has hardcoded 'wiki' namespaces
# for redirects.
# We insert those urlpaths manually so that we can still provide the same 
# app_name pattern ('spaces_<pluginname>') as all the other Spaces plugins
# while keeping things mostly DRY.
wiki_url_patterns = [
    re_path('^notes/(?P<path>.+/|)$', views.SpaceArticleView.as_view(), name='get'),
    re_path('^notes/(?P<path>.+/|)_create/$', views.SpaceCreate.as_view(), name='create'),
    re_path('^notes/(?P<path>.+/|)_deleted/$', views.SpaceDeleted.as_view(), name='deleted'),
]

app_name="spaces_wiki"
urlpatterns = spaces_wiki_url_patterns + SpaceWikiURLPatterns().get_urls()

spaces_wiki/forms.py
import itertools
from django import forms
from django.utils.text import slugify
from django.utils.translation import ugettext as _
from wiki import models
from wiki.forms import CreateForm, DeleteForm

class SpaceCreateForm(CreateForm):
    """
        Variant of wiki.forms.CreateForm. Makes slug optional and automatically
        generates unique slug if empty or already existing.
    """

    slug = forms.SlugField(
        label=_('Slug'),
        help_text=_(
            "This will be the address where your article can be found. Use only alphanumeric characters and - or _. Note that you cannot change the slug after creating the article."),
        max_length=models.URLPath.SLUG_MAX_LENGTH,
        required=False)

    def clean_slug(self):
        slug = self.cleaned_data['slug']
        if not slug:
            title = self.cleaned_data['title'] if 'title' in self.cleaned_data else ''
            slug = title
        else:
            if slug.startswith("_"):
                raise forms.ValidationError(
                _('A slug may not begin with an underscore.'))
            if slug == 'admin':
                raise forms.ValidationError(
                _("'admin' is not a permitted slug name."))
        max_length = models.URLPath.SLUG_MAX_LENGTH
        start_slug = slug = slugify(slug)[:max_length]
        for x in itertools.count(1):
            if not models.URLPath.objects.filter(
                slug__iexact=slug,
                parent=self.urlpath_parent).exists():
                break
            slug = '%s%d' % (start_slug[:max_length - len(str(x))], x)
        return slug

class SpaceDeleteForm(DeleteForm):

    confirm = None
    purge = None

    def clean(self):
        cd = self.cleaned_data
        if cd['revision'] != self.article.current_revision:
            raise forms.ValidationError(
                _(
                    'While you tried to delete this article, it was modified. TAKE CARE!'))
        return cd

spaces_wiki/templates/spaces_wiki/article.html
{% extends "spaces_wiki/base.html" %}
{% load wiki_tags i18n sekizai_tags %}

{% block wiki_pagetitle %}{{ article.current_revision.title }}{% endblock %}
{% block wiki_breadcrumbs %}
<div class="col-md-12">
{% include "spaces_wiki/includes/breadcrumbs.html" %}
</div>
{% endblock %}

{% block wiki_contents %}
<div class="col-md-9">
  <div id="article-container" class="panel panel-default">
  <div class="panel-body">

	  {% block article_menu %}
        <ul class="nav nav-tabs" id="article-menu">
          {% include "spaces_wiki/includes/article_menu.html" %}
        </ul>
	  {% endblock article_menu %}

        <h1 id="article-title">{% block wiki_contents_heading %}
          {{ article.current_revision.title }}
			{% endblock %}
          <small style="font-size:14px;vertical-align:middle;">
            {% if urlpath.parent %}
            <a href="{% url 'spaces_wiki:get' path=urlpath.path %}" title="{% trans 'Direkt link to this article' %}"><span class="icon icon-link"></span></a>
            {% endif %}
            {% if article.current_revision.locked %}
              <span class="icon icon-lock"></span> {% trans "locked" %}
            {% endif %}
          </small>
        </h1>


    <div>
      {% block wiki_contents_tab %}
      {% endblock %}
	  {% block last_change %}
	  <span class="pull-right text-muted m-t-md">
	  {% trans "Last change:" %} {{ article.current_revision.modified }}
	  </span>
	  {% endblock %}
    </div>
  </div>
  </div>
</div>

<div class="col-md-3">
{% include 'spaces_wiki/includes/toc.html' %}
</div>


{% endblock %}


{% block wiki_footer_prepend %}
{% endblock %}

spaces_wiki/templates/spaces_wiki/base.html
{% extends 'collab/plugin.html' %}

{% block body_class %}{{ block.super }} wiki{% endblock %}

{% block content %}
{# Reserved for breadcrumbs #}
{% block wiki_breadcrumbs %}{% endblock %}
      
{# Main page contents go here #}
{% block wiki_contents %}{% endblock %}

{% block wiki_footer_prepend %}
{% endblock %}
{% endblock content %}

spaces_wiki/templates/spaces_wiki/create.html
{% extends "spaces_wiki/base.html" %}
{% load wiki_tags i18n sekizai_tags staticfiles %}


{% block wiki_pagetitle %}{% trans "Add new article" %}{% endblock %}

{% block wiki_contents %}

  {% addtoblock "js" %}
  <script type="text/javascript" src="{% static "admin/js/urlify.js" %}"></script>
  <script type="text/javascript">
  {% if not create_form.slug.value %}
  //<![CDATA[	
  (function($) {
	  $(document).ready(function (){
		  $("#id_title").keyup(function () {
			  var e = $("#id_slug")[0];
			  if(!e._changed) {
			    slug = window.URLify(this.value, 50);
				  e.value = slug;
			  }
	      });
	  });
  })(jQuery);
  //]]>
  {% endif %}
  </script>
  {% endaddtoblock %}

  {% include "spaces_wiki/includes/editormedia.html" %}
  <h1 class="page-header">{% trans "Add new article" %}</h1>
  
  <form method="POST" class="" id="createForm">
    {% wiki_form create_form %}
	{% include "spaces_notifications/form.html" %}
    <div class="form-group form-actions">
      <div class="">
        <a href="{% url 'spaces_wiki:get' path=parent_urlpath.path %}" class="btn btn-default m-r-md">
          <span class="icon icon-level-up"></span>
          {% trans "Go back" %}
        </a>
        <button type="submit" name="save_changes" class="btn btn-primary">
          <span class="icon icon-plus"></span>
          {% trans "Create article" %}
        </button>
      </div>  
    </div>  
  </form>

{% endblock %}

spaces_wiki/templates/spaces_wiki/delete.html
{% extends "spaces_wiki/base.html" %}
{% load wiki_tags i18n sekizai_tags %}


{% block wiki_pagetitle %}{% trans "Delete article" %}{% endblock %}

{% block wiki_contents %}
  <h1 class="page-header">{% trans "Delete" context "article name follows" %} "{{ article.current_revision.title }}"</h1>
  
  {% if cannot_delete_root %}
    <p class="lead">{% trans "You cannot delete a root article." %}</p>
    <p><a href="{% url 'spaces_wiki:get' path=urlpath.path article_id=article.id %}">{% trans "Go back" %}</a></p>
  {% else %}
  
    {% if cannot_delete_children %}
      
      <p class="alert alert-error"><strong>{% trans "You cannot delete this article because you do not have permission to delete articles with children. Try to remove the children manually one-by-one." %}</strong></p>
      
    {% endif %}
      
    {% if delete_children %}

      <p class="lead">{% trans "You are deleting an article. This means that its children will be deleted as well." %}</p>
      
      <h2>{% trans "Articles that will be deleted" %}</h2>
      
      <ul>
        {% for child in delete_children %}
        <li><a href="{% url 'spaces_wiki:get' article_id=child.article.id %}" target="_blank">{{ child.article }}</a></li>
        {% if delete_children_more %}
        <li><em>{% trans "...and more!" %}</em></li>
        {% endif %}
        {% endfor %}
      </ul>
    
    {% endif %}
    
    {% if not cannot_delete_children %}
    <p class="lead">{% trans "You are deleting an article. Please confirm." %}</p>

    <form method="POST" class="form-horizontal">
      {% wiki_form delete_form %}
      <div class="form-group form-actions">
        <div class="col-lg-10">
		  {% if urlpath.path %}
            <a href="{% url 'spaces_wiki:get' path=urlpath.path %}" class="btn btn-default m-r-md">
		  {% else %}
            <a href="{% url 'spaces_wiki:get' article_id=article.id %}" class="btn btn-default m-r-md">
		  {% endif %}
            <span class="icon icon-level-up"></span>
            {% trans "Go back" %}
          </a>
          <button type="submit" name="save_changes" class="btn btn-danger">
            <span class="icon icon-trash"></span>
            {% trans "Delete article" %}
          </button>
        </div>
      </div>  
    </form>
    {% endif %}
 
  {% endif %}

{% addtoblock "js" %}
<script type="text/javascript">
  $('#id_revision').val('{{ article.current_revision.id }}');
</script>
{% endaddtoblock %}

{% endblock %}

spaces_wiki/templates/spaces_wiki/deleted.html
{% extends "spaces_wiki/base.html" %}
{% load spaces_wiki_tags wiki_tags i18n sekizai_tags %}


{% block wiki_pagetitle %}{% trans "Article deleted" %}{% endblock %}

{% block wiki_contents %}
<div class="panel panel-default">
  <div class="panel-body">
    <h1 class="page-header">{% trans "Article deleted" %}</h1>

  
  <p class="lead">
  {% trans "The article you were looking for has been deleted." %}  
  </p>
  
  
  {% if not article.current_revision.locked or article|can_delete:user %}
    <div class="panel panel-default" style="{% hidden_if_not_owner user article space %}">
      <div class="panel panel-body">
        <h2 >{% trans "Restore" %}</h2>
        <p >{% trans "You may restore this article and its children by clicking restore." %}</p>
          <a href="{% url 'spaces_wiki:root' %}" class="btn btn-default m-r-md">
            <span class="icon icon-level-up"></span>
            {% trans "Cancel" %}
          </a>
          <a href="?restore=1" class="btn btn-primary">
            <span class="icon icon-ccw"></span>
            {% trans "Restore" %}
          </a>
      </div>
	</div>
  {% endif %}

{% comment %}  
{# omitting purging so the user experience across other plugins is more similar (e.g. blog has undelete, too, but no purge). #}
  {% if article|can_moderate:user %}
    <div class="panel panel-default">
      <div class="panel-body">
        <h2>{% trans "Purge deletion" %}</h2>
        <p>{% trans "You may remove this article and any children permanently and free their slugs by clicking the below button. This action cannot be undone." %}</p>
        <form method="POST" class="form form-inline">
          {% csrf_token %}
          {% wiki_form purge_form %}
            <button class="btn btn-default">
              <span class="fa fa-remove"></span>
              {% trans "Purge" %}
            </button>
        </form>
      </div>
    </div>
  {% endif %}
{% endcomment %}
  </div>
 
{% endblock %}

spaces_wiki/templates/spaces_wiki/edit.html
{% extends "spaces_wiki/article.html" %}
{% load wiki_tags i18n %}


{% block wiki_pagetitle %}{% trans "Edit" %}: {{ article.current_revision.title }}{% endblock %}

{% block wiki_contents_tab %}

<div class="">

  <div class="">
    <form method="POST" class="" id="article_edit_form">
      <input type="hidden" name="save" value="1" />
      <input type="hidden" name="preview" value="1" />
      {% with edit_form as form %}
        {% include "spaces_wiki/includes/editor.html" %}
      {% endwith %}
{% include "spaces_notifications/form.html" %}
    </form>
  </div>
</div>

<div style="clear: both"></div>



<div class="form-group form-actions" id="wikiEditForm">
  <div class="">
    <div class="">

      <a class="btn btn-default" id="previewButton" href="#"
		  {% if urlpath.path %}
			data-action="{% url 'spaces_wiki:preview' path=urlpath.path %}" 
		  {% else %}
			data-action="{% url 'spaces_wiki:preview' article_id=article.id %}"			
		  {% endif %}
	  >


	
        <span class="icon icon-eye"></span>
        {% trans "Preview" %}
      </a>

      <a class="btn btn-primary" id="saveButton" href="#"
	    {% if urlpath.path %}
			data-action="{% url 'spaces_wiki:edit' path=urlpath.path %}"
	    {% else %}
			data-action="{% url 'spaces_wiki:edit' article_id=article.id %}"
  	    {% endif %}
	  >

        <span class="icon icon-check"></span>
        {% trans "Save changes" %}
      </a>
      {% if article|can_delete:user %}
        {% if urlpath.path %}
        <a href="{% url 'spaces_wiki:delete' path=urlpath.path %}" class="btn btn-danger pull-right">
        {% else %}
        <a href="{% url 'spaces_wiki:delete' article_id=article.id %}" class="btn btn-danger pull-right">
        {% endif %}
        <span class="icon icon-trash"></span>
        {% trans "Delete article" %}
      </a>
      {% endif %}
    </div>
  </div>
</div>


<div class="modal fade wiki-modal" id="previewModal">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-body">
        <iframe name="previewWindow" frameborder="0" src="{% url 'collab:empty_iframe' %}" width="100%" height="50%"></iframe>
      </div>
      <div class="modal-footer">
        <a href="#" class="btn btn-default btn-lg" id="modalCloseButton" data-dismiss="modal">
          <span class="icon icon-level-up"></span>
          {% trans "Back to editor" %}
        </a>
        <a class="btn btn-lg btn-primary" id="modalSaveButton" href="#"
		  {% if urlpath.path %}
			data-action="{% url 'spaces_wiki:edit' path=urlpath.path %}"
	      {% else %}
			data-action="{% url 'spaces_wiki:edit' article_id=article.id %}"
  		  {% endif %}
		>
          <span class="icon icon-check"></span>
          {% trans "Save changes" %}
        </a>
      </div>
    </div>
  </div>
</div>
{% endblock %}


{% block article_menu %}{% endblock article_menu %} 
{% block last_change %}{% endblock %}

spaces_wiki/templates/spaces_wiki/history.html
{% extends "spaces_wiki/article.html" %}
{% load wiki_tags i18n sekizai_tags staticfiles %}


{% block wiki_pagetitle %}{% trans "History" %}: {{ article.current_revision.title }}{% endblock %}

{% block wiki_contents_tab %}


{% addtoblock "js" %}
<script type="text/javascript" src="{% static "wiki/js/core.js" %}"></script>
<script type="text/javascript" src="{% static "wiki/js/diffview.js" %}"></script>
<script type="text/javascript" src="{% static "wiki/js/diff.js" %}"></script>
{% endaddtoblock %}
{% addtoblock "css" %}
<style type="text/css">
  td.linenumber {
    width: 20px;
  }
  tr.insert td {
    background-color: #DFC;
  }
  tr.delete td {
    background-color: #FDC;
  }
  tr.equal td {
    background-color: #F2F2F2;
  }
  
  .diff-container td {
    white-space: pre; font-family: monospace;
  }
  .diff-container td,
  .diff-container th {
    padding: 2px 7px;
    border-right: 1px solid #DDD;    
  }
  .diff-container td:last-child,
  .diff-container th:last-child {
    border-right: none;
  }
  .diff-container table {
    border-top: 1px solid #DDD;    
  }
</style>
{% endaddtoblock %}

<p class="lead">
  {% trans "Click each revision to see a list of edited lines. Click the Preview button to see how the article looked at this stage. At the bottom of this page, you can change to a particular revision." %}
</p>

<form method="GET">
  <div class="tab-content" style="overflow: visible;">
    {% for revision in revisions %}
      <div class="panel-group" id="accordion{{ revision.revision_number }}">
        <div class="panel panel-default">
          <div class="panel-heading">
            <a class="panel-toggle" style="float: left;" href="#collapse{{ revision.revision_number }}" onclick="get_diff_json('{% url 'spaces_wiki:diff' revision.id %}', $('#collapse{{ revision.revision_number }}'))">
              {% if revision == article.current_revision %}
                <i class="fa fa-flag"></i>
              {% else %}
                <i class="fa fa-plus"></i>
              {% endif %}
              {% include "wiki/includes/revision_info.html" with current_revision=article.current_revision %}
              <div class="text-muted">
                <small>
                {% if revision.user_message %}
                  {{ revision.user_message }}
                {% elif revision.automatic_log %}
                  {{ revision.automatic_log }}
                {% else %}
                  ({% trans "no log message" %})
                {% endif %}
                </small>
              </div>
            </a>
            <div class="progress progress-striped active" style="display: none; width: 40px; float: left; margin-top: 7px; margin-bottom: -7px;">
              <div class="bar" style="width: 100%;"></div>
            </div>
            <div class="pull-right" style="vertical-align: middle; margin: 8px 8px;">
              {% if revision == article.current_revision %}
              <a href="#" class="btn btn-default disabled">
                <span class="fa fa-lock fa-fw"></span>
                {% trans "Preview this revision" %}
              </a>
              {% else %}
			  	{% if urlpath.path %}
	              <button type="submit" class="btn btn-default" onclick="$('#previewModal').modal('show'); this.form.target='previewWindow'; this.form.r.value='{{ revision.id }}'; this.form.action='{% url 'spaces_wiki:preview_revision' article.id %}'; $('#previewModal .switch-to-revision').attr('href', '{% url 'spaces_wiki:change_revision' path=urlpath.path revision_id=revision.id %}')">
				{% else %}
	              <button type="submit" class="btn btn-default" onclick="$('#previewModal').modal('show'); this.form.target='previewWindow'; this.form.r.value='{{ revision.id }}'; this.form.action='{% url 'spaces_wiki:preview_revision' article.id %}'; $('#previewModal .switch-to-revision').attr('href', '{% url 'spaces_wiki:change_revision' article_id=article.id revision_id=revision.id %}')">
				{% endif %}
                <span class="fa fa-eye fa-fw"></span>
                {% trans "Preview this revision" %}
              </button>
              {% endif %}

              {% if article|can_write:user and not article.current_revision.locked %}
				{% if urlpath.path %}
              	  <input type="radio"{% if revision == article.current_revision %} disabled="true"{% endif %} style="margin: 0 10px;" value="{{ revision.id }}" name="revision_id" switch-button-href="{% url 'spaces_wiki:change_revision' path=urlpath.path revision_id=revision.id %}" merge-button-href="{% url 'spaces_wiki:merge_revision_preview' article_id=article.id revision_id=revision.id %}" merge-button-commit-href="{% url 'spaces_wiki:merge_revision' path=urlpath.path revision_id=revision.id %}" />
				{% else %}
	              <input type="radio"{% if revision == article.current_revision %} disabled="true"{% endif %} style="margin: 0 10px;" value="{{ revision.id }}" name="revision_id" switch-button-href="{% url 'spaces_wiki:change_revision' path=urlpath.path revision_id=revision.id %}" merge-button-href="{% url 'spaces_wiki:merge_revision_preview' article_id=article.id revision_id=revision.id %}" merge-button-commit-href="{% url 'spaces_wiki:merge_revision' article_id=article.id revision_id=revision.id %}" />
				{% endif %}
              {% endif %}
            </div>
            <div style="clear: both"></div>
          </div>
          <div id="collapse{{ revision.revision_number }}" class="panel-collapse collapse">
            <div class="panel-body diff-container" style="padding: 0;">
              <dl class="dl-horizontal">
                <dt>{% trans "Auto log:" %}</dt>
                <dd>{{ revision.automatic_log|default:"-"|linebreaksbr }}</dd>
              </dl>
              <table class="table table-condensed" style="margin: 0; border-collapse: collapse;">
                <thead>
                  <tr>
                    <th class="linenumber">{% if revision.previous_revision %}#{{revision.previous_revision.revision_number}}{% endif %}</th>
                    <th class="linenumber">#{{revision.revision_number}}</th>
                    <th>{% trans "Change" %}</th>
                  </tr>
                </thead>
              </table>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
    
    {% include "wiki/includes/pagination.html" %}
    
    {% if revisions.count > 1 and article|can_write:user and not article.current_revision.locked %}

    <div class="form-group form-actions">
      <div class="pull-right">
{% comment %}
{# skipping merge feature for now. The only needed change to make it work should be the return url. should be set to 'spaces_wiki:get'. #}              
        <button type="submit" name="preview" value="1" class="btn btn-default" onclick="$('#mergeModal').modal('show'); this.form.target='mergeWindow'; this.form.action=$('input[type=radio]:checked').attr('merge-button-href'); $('.merge-revision-commit').attr('href', $('input[type=radio]:checked').attr('merge-button-commit-href'))">
          <span class="fa fa-random"></span>
          {% trans "Merge selected with current..." %}
        </button>
{% endcomment %}    
		<a href="{% if urlpath.path %}{% url 'spaces_wiki:get' path=urlpath.path %}{% else %}{% url 'spaces_wiki:get' article_id=article.id %}{% endif %}" class="btn btn-default m-r-md">
		  <span class="icon icon-level-up"></span>
		  {% trans 'Go back' %}
		</a>
        <button type="submit" name="save" value="1" class="btn btn-primary" onclick="this.form.target='_self'; this.form.action=$('input[type=radio]:checked').attr('switch-button-href')">
          <span class="fa fa-flag"></span>
          {% trans "Switch to selected version" %}
        </button>
      </div>
      <div style="clear:both"></div>
    </div>
    
    {% endif %}
    
  </div>
  <input type="hidden" name="r" value="" />
  <div class="modal fade wiki-modal" id="previewModal">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-body">
          <iframe name="previewWindow" frameborder="0" width="99%" height="50%" src="{% url 'collab:empty_iframe' %} "></iframe>
        </div>
        <div class="modal-footer">
          <a href="#" class="btn btn-default btn-lg" data-dismiss="modal">
            <span class="fa fa-arrow-circle-left"></span>
            {% trans "Back to history view" %}
          </a>
          {% if article|can_write:user %}
          <a href="#" class="btn btn-lg btn-primary switch-to-revision">
            <span class="fa fa-flag"></span>
            {% trans "Switch to this version" %}
          </a>
          {% else %}
            <a href="#" class="btn btn-lg btn-primary disabled">
              <span class="fa fa-lock"></span>
              {% trans "Switch to this version" %}
            </a>                    
          {% endif %}
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade wiki-modal" id="mergeModal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1>{% trans "Merge with current" %}</h1>
          <p class="lead"><span class="fa fa-info-circle"></span> {% trans "When you merge a revision with the current, all data will be retained from both versions and merged at its approximate location from each revision." %} <strong>{% trans "After this, it's important to do a manual review." %}</strong></p>
        </div>
        <div class="modal-body">
          <iframe name="mergeWindow" frameborder="0" style="min-height: 0;"></iframe>
        </div>
        <div class="modal-footer">
          <a href="#" class="btn btn-default btn-lg" data-dismiss="modal">
            <span class="fa fa-arrow-circle-left"></span>
            {% trans "Back to history view" %}
          </a>
          {% if article|can_write:user %}
          <a href="#" class="btn btn-lg btn-primary merge-revision-commit">
            <span class="fa fa-file"></span>
            {% trans "Create new merged version" %}
          </a>                    
          {% else %}
            <a href="#" class="btn btn-lg btn-primary disabled">
              <span class="fa fa-lock"></span>
              {% trans "Create new merged version" %}
            </a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</form>
  
{% endblock %}

{% block article_menu %}{% endblock article_menu %} 
{% block last_change %}{% endblock %}

spaces_wiki/templates/spaces_wiki/icon.html
<span class="icon icon-book"></span>

spaces_wiki/templates/spaces_wiki/index.html
{% extends "spaces_wiki/article.html" %}
{% load wiki_tags i18n humanize %}


{% block wiki_pagetitle %}{% trans "Listing articles in" %} {{ article.current_revision.title }}{% endblock %}

{% block wiki_contents_heading %}
  {% trans 'Notebook' %}
{% endblock %}

{% block wiki_contents_tab %}

{% url 'spaces_wiki:dir' urlpath.path as self_url %}

<form class="form-search directory-toolbar">
<div class="well well-small">
  <div class="btn-group pull-left">
    <a href="{% url 'spaces_wiki:create' path=urlpath.path %}" class="btn btn-default">
      <span class="icon icon-plus"></span>
      {% trans "Add article" %}
    </a>
  </div>
  <div class="pull-right">
    {{ filter_form.query }}
  </div>
  {% if filter_query %}
    <div class="pull-right filter-clear">
      <a href="{{ self_url }}">({% trans "clear" %})</a>
    </div>
  {% endif %}

  <div class="clearfix"></div>
</div>
</form>

<table class="table table-striped">
  <tr>
    <th>{% trans "Title" %}</th>
    <th>{% trans "Last Change" %}</th>
  </tr>
  {% for urlpath in directory %}
	{% if not urlpath.article.current_revision.deleted %}
    <tr>
      <td>
        <a href="{% url 'spaces_wiki:get' path=urlpath.path %}"> {{ urlpath.article.current_revision.title }} </a> 
        <a href="{% url 'spaces_wiki:dir' path=urlpath.path %}" class="list-children"> › </a>
		{% comment %}
        {% if urlpath.article.current_revision.deleted %}
          <span class="icon icon-trash"></span>
        {% endif %}
        {% if urlpath.article.current_revision.locked %}
          <span class="icon icon-lock"></span>
        {% endif %}
		{% endcomment %}
      </td>
      <td>
        {{ urlpath.article.modified }}
      </td>
    </tr>
	{% endif %}
    {% empty%}
    <tr>
      <td colspan="100">
        <em>{% trans "There are no articles in this level" %}</em>
      </td>
    </tr>
  {% endfor %}
</table>

{% include "wiki/includes/pagination.html" %}

{% endblock %}

{% block article_menu %}{% endblock %} 
{% block wiki_footer_prepend %}{% endblock %}

spaces_wiki/templates/spaces_wiki/view.html
{% extends "spaces_wiki/article.html" %}
{% load wiki_tags i18n sekizai_tags %}


{% block wiki_contents_tab %}
  {% wiki_render article %}
{% endblock %}